### ISSUE TITLE
Will there be support?

### ISSUE THREAD

**Issue by MeshBenth** [0xd4d/de4dot#186] opened 2018-10-23 16:46 UTC
Will CliSecure 6.4.0.31 support? CSVM Error

**Comment by 0xd4d** [comment] 2018-10-24 11:47
Dupe of https://github.com/0xd4d/de4dot/issues/155

**Closed by 0xd4d** 2018-10-24 11:47 UTC

**Comment by mayankbudhiraja3** [comment] 2018-12-26 11:10
Same! When will we get the support?
