### ISSUE TITLE
de4dot.code.deobfuscators.Agile_NET 

### ISSUE THREAD

**Issue by ilmir15** [0xd4d/de4dot#192] opened 2018-11-16 16:52 UTC
Hi dear. Can you help to update for popular Agile deodfs .  
On MethodsDecrypter on MethodBodyParser cannot to get MethodBodyHeader

//???+++       b=0x61 (97)  b & 3 = 1   b & 3 = 7 
if ((b & 3) == 2)   else if ((b & 7) == 3)  throw new InvalidMethodBody();
I wil very funkfull for it . ilmir-zr@yandex.ru 
 
static MethodBodyHeader ParseMethodBody2(ref DataReader reader, out byte[] code, out byte[] extraSections) {
			var mbHeader = new MethodBodyHeader();
			
			uint codeOffset;
			byte b = Peek(ref reader);
			if ((b & 3) == 2) {
				mbHeader.flags = 2;
				mbHeader.maxStack = 8;
				mbHeader.codeSize = (uint)(reader.ReadByte() >> 2);
				mbHeader.localVarSigTok = 0;
				codeOffset = 1;
			}
			else if ((b & 7) == 3) {
				mbHeader.flags = reader.ReadUInt16();
				codeOffset = (uint)(4 * (mbHeader.flags >> 12));
				if (codeOffset != 12)
					throw new InvalidMethodBody();
				mbHeader.maxStack = reader.ReadUInt16();
				mbHeader.codeSize = reader.ReadUInt32();
				if (mbHeader.codeSize > int.MaxValue)
					throw new InvalidMethodBody();
				mbHeader.localVarSigTok = reader.ReadUInt32();
				if (mbHeader.localVarSigTok != 0 && (mbHeader.localVarSigTok >> 24) != 0x11)
					throw new InvalidMethodBody();
			}
			else
				throw new InvalidMethodBody();

**Comment by 0xd4d** [comment] 2018-11-16 18:02
Dupe of #155

**Closed by 0xd4d** 2018-11-16 18:02 UTC
