### ISSUE TITLE
decrypt error

### ISSUE THREAD

**Issue by jyhojyho** [0xd4d/de4dot#161] opened 2018-06-10 17:00 UTC
de4dot v3.1.41592.3405 Copyright (C) 2011-2015 de4dot@gmail.com
Latest version and source code: https://github.com/0xd4d/de4dot

  1: Unknown
100: Agile.NET
  0: Babel .NET
  0: CodeFort
  0: CodeVeil
  0: CodeWall
Deobfuscating control flow: System.Void <Module>::.cctor() (06000001)
Deobfuscating control flow: System.Void <AgileDotNetRTPro>::Initialize() (06000AF9)
Deobfuscating control flow: System.Void <AgileDotNetRTPro>::PostInitialize() (06000AFA)
  0: Confuser
  0: Crypto Obfuscator
Deobfuscating control flow: System.Void <Module>::.cctor() (06000001)
  0: DeepSea
  0: Dotfuscator
  0: .NET Reactor 3.x
  0: .NET Reactor 4.x
  0: Eazfuscator.NET
  0: Goliath.NET
  0: ILProtector
  0: MaxtoCode
  0: MPRESS
  0: Rummage
  0: Skater .NET
  0: SmartAssembly
  0: Spices.Net
  0: Xenocode
Detected CliSecure (C:\Users\XX\Desktop\de4dot\HPC.dll)
Cleaning C:\Users\XX\Desktop\de4dot\HPC.dll
Using dynamic method decryption
ERROR:
ERROR:
ERROR:
ERROR: ------------------------------------------------------------------------------
ERROR: Stack trace:
ERROR:
ERROR: Server stack trace:
ERROR:    at System.Runtime.CompilerServices.RuntimeHelpers._RunModuleConstructor(RuntimeModule module)
ERROR:    at de4dot.mdecrypt.DynamicMethodsDecrypter.LoadObfuscator()
ERROR:    at AssemblyData.MethodDecrypterService.LoadObfuscator(String filename)
ERROR:    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
ERROR:    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
ERROR:
ERROR: Exception rethrown at [0]:
ERROR:    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
ERROR:    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
ERROR:    at AssemblyData.IMethodDecrypterService.LoadObfuscator(String filename)
ERROR:    at de4dot.code.deobfuscators.MethodsDecrypter.Decrypt2(ServerClrVersion serverVersion, String filename, Byte[] moduleCctorBytes)
ERROR:    at de4dot.code.deobfuscators.MethodsDecrypter.Decrypt(ServerClrVersion serverVersion, String filename, Byte[] moduleCctorBytes)
ERROR:    at de4dot.code.deobfuscators.MethodsDecrypter.Decrypt(ModuleDef module, Byte[] moduleCctorBytes)
ERROR:    at de4dot.code.deobfuscators.Agile_NET.MethodsDecrypter.Decrypt(MyPEImage peImage, ModuleDefMD module, CliSecureRtType csRtType, DumpedMethods& dumpedMethods)
ERROR:    at de4dot.code.deobfuscators.Agile_NET.Deobfuscator.GetDecryptedModule(Int32 count, Byte[]& newFileData, DumpedMethods& dumpedMethods)
ERROR:    at de4dot.code.ObfuscatedFile.Deobfuscate()
ERROR:    at de4dot.cui.FilesDeobfuscator.DeobfuscateAllFiles(IEnumerable`1 allFiles)
ERROR:    at de4dot.cui.FilesDeobfuscator.DeobfuscateAll()
ERROR:    at de4dot.cui.FilesDeobfuscator.DoIt()
ERROR:    at de4dot.cui.Program.Main(String[] args)
ERROR:
ERROR:
ERROR: Caught an exception:
ERROR:
ERROR: ------------------------------------------------------------------------------
ERROR: Message:
ERROR:   The type initializer for '<Module>' threw an exception.
ERROR: Type:
ERROR:   System.TypeInitializationException
ERROR: ------------------------------------------------------------------------------
ERROR:
ERROR: Try the latest version!

**Comment by HoLLy-HaCKeR** [comment] 2018-06-11 06:13
Try to use static decryption instead of dynamic decryption. Also, make sure you're running the latest master.

**Comment by jyhojyho** [comment] 2018-06-11 08:18
Could you show me how to use static decryption?. I read `de4dot -h` and try some but none of them work. I'm using latest master.

**Comment by timors** [comment] 2018-06-21 09:10
The Agile.NET can't visit.

**Comment by 0xd4d** [comment] 2018-08-21 09:57
Dupe of #155

**Closed by 0xd4d** 2018-08-21 09:57 UTC
